apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: default
spec:
  clusterIP: 10.43.117.64
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32169
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-nginx
  sessionAffinity: None
  type: NodePort
